module.exports = [
  'All of me a wound to close, but I leave the whole thing open.🎶',
  'Your phone was playing Towers and I...🎶',
  "Can't wait what to see what you do with it!",
  "Those are the pearls that were his eyes 🌊",
  'Same bat time, same bat channel. 🦇',
  'Be kind, rewind.',
  'Every day is an adventure. ✨',
  "You miss 100% of the shots you don't take. 🏀",
  "It's like sunshine on a rainy day. 🌦",
  "💪 You've got this.",
  "You're a rockstar. 🤘",
  'Have you gone for a walk today? 🚶',
  'Be kind to people. Including yourself.',
  'Woohoo!! ✨',
  "Let's do some celebratory jumping jacks! ⭐️",
  "Let's party 🥳",
  'All good vibes. 🌈',
  '🎉🎉🎉🎉🎉',
  'You are an unstoppable force of nature.',
  'You belong in this world ❤️',
  'Live your best life ❤️',
  "Wherever it takes me, I'm down for the ride. 🎶",
];
